from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import MedicalImageViewSet

# 1. Create a router instance
router = DefaultRouter()

# 2. Register your ViewSet with a base name
# This will automatically generate the following routes:
# - POST /translations/        (for create/upload)
# - GET /translations/{id}/    (for retrieve/status check)
router.register(r'translations', MedicalImageViewSet, basename='translation')

# 3. Define the urlpatterns for this app
urlpatterns = [
    # Include all the routes generated by the router (e.g., /translations/)
    path('', include(router.urls)),
    
    # You can add other custom paths here if needed later
]
