# Generated by Django 6.0 on 2025-12-26 22:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='medical_images/%Y/%m/%d/')),
                ('image_type', models.CharField(blank=True, choices=[('DICOM', 'DICOM File'), ('IMAGE', 'Standard Image (PNG/JPG)')], max_length=20)),
                ('modality', models.CharField(choices=[('CT', 'CT'), ('MRI', 'MRI')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('translation_status', models.CharField(default='PENDING', max_length=50)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_type_detected', models.CharField(max_length=200)),
                ('observations', models.JSONField(default=list)),
                ('potential_conditions', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('raw_analysis', models.TextField()),
                ('disclaimer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='translate.medicalimage')),
            ],
            options={
                'verbose_name_plural': 'Image Analyses',
            },
        ),
    ]
