# Generated by Django 5.2.10 on 2026-01-18 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='translated_image',
            field=models.ImageField(blank=True, null=True, upload_to='translated_images/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='DICOMData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(blank=True, max_length=128, null=True)),
                ('study_date', models.CharField(blank=True, max_length=20, null=True)),
                ('modality', models.CharField(blank=True, max_length=16, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=256, null=True)),
                ('series_description', models.CharField(blank=True, max_length=256, null=True)),
                ('body_part_examined', models.CharField(blank=True, max_length=128, null=True)),
                ('dicom_metadata', models.JSONField(blank=True, default=dict)),
                ('medical_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_data', to='translate.medicalimage')),
            ],
        ),
    ]
